# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=0.10.0
maven_group=ir.mehradn
archives_base_name=rollback

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=[VERSIONED]
loader_version=0.16.10
fabric_version=[VERSIONED]
parchment_version=[VERSIONED]

# Dependencies
